/**
 * Enumerations used across MuleNet 3.0 platform
 */

export enum TransactionType {
  WIRE_TRANSFER = 'WIRE_TRANSFER',
  ACH = 'ACH',
  CARD_PAYMENT = 'CARD_PAYMENT',
  CRYPTO_TRANSFER = 'CRYPTO_TRANSFER',
  CASH_DEPOSIT = 'CASH_DEPOSIT',
  CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
}

export enum DataFormat {
  ISO20022 = 'ISO20022',
  SWIFT_MT103 = 'SWIFT_MT103',
  STIX21 = 'STIX21',
  INTERNAL = 'INTERNAL',
}

export enum EntityType {
  INDIVIDUAL = 'INDIVIDUAL',
  BUSINESS = 'BUSINESS',
  ACCOUNT = 'ACCOUNT',
  DEVICE = 'DEVICE',
  IP_ADDRESS = 'IP_ADDRESS',
  CRYPTO_WALLET = 'CRYPTO_WALLET',
}

export enum IdentifierType {
  SSN = 'SSN',
  PASSPORT = 'PASSPORT',
  DRIVERS_LICENSE = 'DRIVERS_LICENSE',
  TAX_ID = 'TAX_ID',
  ACCOUNT_NUMBER = 'ACCOUNT_NUMBER',
  IBAN = 'IBAN',
  SWIFT_BIC = 'SWIFT_BIC',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  DEVICE_ID = 'DEVICE_ID',
  IP_ADDRESS = 'IP_ADDRESS',
  CRYPTO_ADDRESS = 'CRYPTO_ADDRESS',
}

export enum AlertTier {
  INFORMATIONAL = 'INFORMATIONAL', // Score 0.0-0.3
  MONITORING = 'MONITORING', // Score 0.3-0.6
  INVESTIGATION = 'INVESTIGATION', // Score 0.6-0.85
  CRITICAL = 'CRITICAL', // Score 0.85-1.0
}

export enum RiskFactorType {
  VELOCITY_ANOMALY = 'VELOCITY_ANOMALY',
  STRUCTURAL_PATTERN = 'STRUCTURAL_PATTERN',
  TEMPORAL_PATTERN = 'TEMPORAL_PATTERN',
  ENTITY_RISK = 'ENTITY_RISK',
  NETWORK_CENTRALITY = 'NETWORK_CENTRALITY',
  CROSS_BORDER = 'CROSS_BORDER',
  ROUND_AMOUNT = 'ROUND_AMOUNT',
  RAPID_MOVEMENT = 'RAPID_MOVEMENT',
  LAYERING = 'LAYERING',
  SMURFING = 'SMURFING',
}

export enum EncryptionScheme {
  CKKS_FHE = 'CKKS_FHE',
  PAILLIER = 'PAILLIER',
  SECURE_AGGREGATION = 'SECURE_AGGREGATION',
}

export enum FindingType {
  MULE_PATTERN = 'MULE_PATTERN',
  VELOCITY_ANOMALY = 'VELOCITY_ANOMALY',
  STRUCTURAL_ANOMALY = 'STRUCTURAL_ANOMALY',
  ENTITY_RISK = 'ENTITY_RISK',
  REGULATORY_CONCERN = 'REGULATORY_CONCERN',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EvidenceType {
  TRANSACTION_PATTERN = 'TRANSACTION_PATTERN',
  GRAPH_STRUCTURE = 'GRAPH_STRUCTURE',
  TEMPORAL_SEQUENCE = 'TEMPORAL_SEQUENCE',
  ENTITY_ATTRIBUTE = 'ENTITY_ATTRIBUTE',
  EXTERNAL_DATA = 'EXTERNAL_DATA',
}

export enum VerificationStatus {
  VERIFIED = 'VERIFIED',
  PARTIALLY_VERIFIED = 'PARTIALLY_VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
  FAILED = 'FAILED',
}

export enum LLMProvider {
  GPT4 = 'GPT4',
  GEMINI = 'GEMINI',
  CLAUDE = 'CLAUDE',
}

export enum Jurisdiction {
  EU_GDPR = 'EU_GDPR',
  UK_GDPR = 'UK_GDPR',
  UK_MLR_2017 = 'UK_MLR_2017',
  INDIA_DPDP_2023 = 'INDIA_DPDP_2023',
  US_GLBA = 'US_GLBA',
  US_BSA = 'US_BSA',
}
